// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ccAzJh4lSV53SjNY6M0k_dBtg0rpanE',
    appId: '1:769429726053:web:2122c17d030e814195378c',
    messagingSenderId: '769429726053',
    projectId: 'flutter-demo-37hr-course-myno',
    authDomain: 'flutter-demo-37hr-course-myno.firebaseapp.com',
    storageBucket: 'flutter-demo-37hr-course-myno.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jovlaRUcCDsHTXDYT2r9Z67CPs7CzZI',
    appId: '1:769429726053:android:9aca5ad8eff9339995378c',
    messagingSenderId: '769429726053',
    projectId: 'flutter-demo-37hr-course-myno',
    storageBucket: 'flutter-demo-37hr-course-myno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuWewC_nre8Wj_ZAtc1mjVCF6WxsWckqc',
    appId: '1:769429726053:ios:783d70baec7c227a95378c',
    messagingSenderId: '769429726053',
    projectId: 'flutter-demo-37hr-course-myno',
    storageBucket: 'flutter-demo-37hr-course-myno.appspot.com',
    iosBundleId: 'com.example.learnflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuWewC_nre8Wj_ZAtc1mjVCF6WxsWckqc',
    appId: '1:769429726053:ios:783d70baec7c227a95378c',
    messagingSenderId: '769429726053',
    projectId: 'flutter-demo-37hr-course-myno',
    storageBucket: 'flutter-demo-37hr-course-myno.appspot.com',
    iosBundleId: 'com.example.learnflutter',
  );
}
